export const properyTypes = [
  {
    label: "Residential",
    value: "Residential",
    subOptions: [
      {
        label: "Bungalows",
        value: "Bungalows",
      },
      {
        label: "Mansions",
        value: "Mansions",
      },
      {
        label: "Villas",
        value: "Villas",
      },
      {
        label: "Town Houses",
        value: "Town Houses",
      },
      {
        label: "Duplexes",
        value: "Duplexes"
      },
      {
        label: "Apartments",
        value: "Apartments",
      },

      {
        label: "Others",
        value: "Others",
      },
    ],
  },
  {
    label: "Commercial",
    value: "Commercial",
    subOptions: [
      {
        label: "Office Spaces",
        value: "Office Spaces",
      },
      {
        label: "Shops",
        value: "shops",
      },
      {
        label: "Stalls",
        value: "Stalls",
      },
      {
        label: "Others",
        value: "Others",
      },
    ],
  },
  {
    label: "Industrial",
    value: "Industrial",
    subOptions: [
      {
        label: "Warehouses",
        value: "Warehouses",
      },
      {
        label: "Go Downs",
        value: "Go Downs",
      },
      {
        label: "Parks",
        value: "Parks",
      },
      {
        label: "Flex Spaces",
        value: "Flex Spaces",
      },
    ],
  },

  {
    label: "Vacational / Social",
    value: "Vacational / Social",
    subOptions: [
      {
        label: "Cabins",
        value: "Cabins",
      },
      {
        label: "Cottages",
        value: "Cottages",
      },
      {
        label: "Vacational Homes",
        value: "Vacational Homes",
      },
      {
        label: "Others",
        value: "Others",
      },
    ],
  },
  {
    label: "Land",
    value: "Land",
    subOptions: [
      {
        label: "Plots",
        value: "Plots",
      },
      {
        label: "Farms",
        value: "Farms",
      },
      {
        label: "Others",
        value: "Others",
      },
    ],
  },
];

export const propertyStatuses = [
  { value: "sale", label: "Sale" },
  { value: "let", label: "Let" },
];

export const currencyOptions = [
  { value: "KES", label: "KES" },
  { value: "USD", label: "USD" },
];

// Countries
export const countries = [
  { "label": "Afghanistan", "value": "Afghanistan" },
  { "label": "Albania", "value": "Albania" },
  { "label": "Algeria", "value": "Algeria" },
  { "label": "Andorra", "value": "Andorra" },
  { "label": "Angola", "value": "Angola" },
  { "label": "Antigua and Barbuda", "value": "Antigua and Barbuda" },
  { "label": "Argentina", "value": "Argentina" },
  { "label": "Armenia", "value": "Armenia" },
  { "label": "Australia", "value": "Australia" },
  { "label": "Austria", "value": "Austria" },
  { "label": "Azerbaijan", "value": "Azerbaijan" },
  { "label": "Bahamas", "value": "Bahamas" },
  { "label": "Bahrain", "value": "Bahrain" },
  { "label": "Bangladesh", "value": "Bangladesh" },
  { "label": "Barbados", "value": "Barbados" },
  { "label": "Belarus", "value": "Belarus" },
  { "label": "Belgium", "value": "Belgium" },
  { "label": "Belize", "value": "Belize" },
  { "label": "Benin", "value": "Benin" },
  { "label": "Bhutan", "value": "Bhutan" },
  { "label": "Bolivia", "value": "Bolivia" },
  { "label": "Bosnia and Herzegovina", "value": "Bosnia and Herzegovina" },
  { "label": "Botswana", "value": "Botswana" },
  { "label": "Brazil", "value": "Brazil" },
  { "label": "Brunei", "value": "Brunei" },
  { "label": "Bulgaria", "value": "Bulgaria" },
  { "label": "Burkina Faso", "value": "Burkina Faso" },
  { "label": "Burundi", "value": "Burundi" },
  { "label": "Cabo Verde", "value": "Cabo Verde" },
  { "label": "Cambodia", "value": "Cambodia" },
  { "label": "Cameroon", "value": "Cameroon" },
  { "label": "Canada", "value": "Canada" },
  { "label": "Central African Republic", "value": "Central African Republic" },
  { "label": "Chad", "value": "Chad" },
  { "label": "Chile", "value": "Chile" },
  { "label": "China", "value": "China" },
  { "label": "Colombia", "value": "Colombia" },
  { "label": "Comoros", "value": "Comoros" },
  { "label": "Congo", "value": "Congo" },
  { "label": "Costa Rica", "value": "Costa Rica" },
  { "label": "Croatia", "value": "Croatia" },
  { "label": "Cuba", "value": "Cuba" },
  { "label": "Cyprus", "value": "Cyprus" },
  { "label": "Czechia", "value": "Czechia" },
  { "label": "Denmark", "value": "Denmark" },
  { "label": "Djibouti", "value": "Djibouti" },
  { "label": "Dominica", "value": "Dominica" },
  { "label": "Dominican Republic", "value": "Dominican Republic" },
  { "label": "Ecuador", "value": "Ecuador" },
  { "label": "Egypt", "value": "Egypt" },
  { "label": "El Salvador", "value": "El Salvador" },
  { "label": "Equatorial Guinea", "value": "Equatorial Guinea" },
  { "label": "Eritrea", "value": "Eritrea" },
  { "label": "Estonia", "value": "Estonia" },
  { "label": "Eswatini", "value": "Eswatini" },
  { "label": "Ethiopia", "value": "Ethiopia" },
  { "label": "Fiji", "value": "Fiji" },
  { "label": "Finland", "value": "Finland" },
  { "label": "France", "value": "France" },
  { "label": "Gabon", "value": "Gabon" },
  { "label": "Gambia", "value": "Gambia" },
  { "label": "Georgia", "value": "Georgia" },
  { "label": "Germany", "value": "Germany" },
  { "label": "Ghana", "value": "Ghana" },
  { "label": "Greece", "value": "Greece" },
  { "label": "Grenada", "value": "Grenada" },
  { "label": "Guatemala", "value": "Guatemala" },
  { "label": "Guinea", "value": "Guinea" },
  { "label": "Guinea-Bissau", "value": "Guinea-Bissau" },
  { "label": "Guyana", "value": "Guyana" },
  { "label": "Haiti", "value": "Haiti" },
  { "label": "Honduras", "value": "Honduras" },
  { "label": "Hungary", "value": "Hungary" },
  { "label": "Iceland", "value": "Iceland" },
  { "label": "India", "value": "India" },
  { "label": "Indonesia", "value": "Indonesia" },
  { "label": "Iran", "value": "Iran" },
  { "label": "Iraq", "value": "Iraq" },
  { "label": "Ireland", "value": "Ireland" },
  { "label": "Israel", "value": "Israel" },
  { "label": "Italy", "value": "Italy" },
  { "label": "Jamaica", "value": "Jamaica" },
  { "label": "Japan", "value": "Japan" },
  { "label": "Jordan", "value": "Jordan" },
  { "label": "Kazakhstan", "value": "Kazakhstan" },
  { "label": "Kenya", "value": "Kenya" },
  { "label": "Kiribati", "value": "Kiribati" },
  { "label": "Kuwait", "value": "Kuwait" },
  { "label": "Kyrgyzstan", "value": "Kyrgyzstan" },
  { "label": "Laos", "value": "Laos" },
  { "label": "Latvia", "value": "Latvia" },
  { "label": "Lebanon", "value": "Lebanon" },
  { "label": "Lesotho", "value": "Lesotho" },
  { "label": "Liberia", "value": "Liberia" },
  { "label": "Libya", "value": "Libya" },
  { "label": "Liechtenstein", "value": "Liechtenstein" },
  { "label": "Lithuania", "value": "Lithuania" },
  { "label": "Luxembourg", "value": "Luxembourg" },
  { "label": "Madagascar", "value": "Madagascar" },
  { "label": "Malawi", "value": "Malawi" },
  { "label": "Malaysia", "value": "Malaysia" },
  { "label": "Maldives", "value": "Maldives" },
  { "label": "Mali", "value": "Mali" },
  { "label": "Malta", "value": "Malta" },
  { "label": "Marshall Islands", "value": "Marshall Islands" },
  { "label": "Mauritania", "value": "Mauritania" },
  { "label": "Mauritius", "value": "Mauritius" },
  { "label": "Mexico", "value": "Mexico" },
  { "label": "Micronesia", "value": "Micronesia" },
  { "label": "Moldova", "value": "Moldova" },
  { "label": "Monaco", "value": "Monaco" },
  { "label": "Mongolia", "value": "Mongolia" },
  { "label": "Montenegro", "value": "Montenegro" },
  { "label": "Morocco", "value": "Morocco" },
  { "label": "Mozambique", "value": "Mozambique" },
  { "label": "Myanmar", "value": "Myanmar" },
  { "label": "Namibia", "value": "Namibia" },
  { "label": "Nauru", "value": "Nauru" },
  { "label": "Nepal", "value": "Nepal" },
  { "label": "Netherlands", "value": "Netherlands" },
  { "label": "New Zealand", "value": "New Zealand" },
  { "label": "Nicaragua", "value": "Nicaragua" },
  { "label": "Niger", "value": "Niger" },
  { "label": "Nigeria", "value": "Nigeria" },
  { "label": "North Korea", "value": "North Korea" },
  { "label": "North Macedonia", "value": "North Macedonia" },
  { "label": "Norway", "value": "Norway" },
  { "label": "Oman", "value": "Oman" },
  { "label": "Pakistan", "value": "Pakistan" },
  { "label": "Palau", "value": "Palau" },
  { "label": "Palestine", "value": "Palestine" },
  { "label": "Panama", "value": "Panama" },
  { "label": "Papua New Guinea", "value": "Papua New Guinea" },
  { "label": "Paraguay", "value": "Paraguay" },
  { "label": "Peru", "value": "Peru" },
  { "label": "Philippines", "value": "Philippines" },
  { "label": "Poland", "value": "Poland" },
  { "label": "Portugal", "value": "Portugal" },
  { "label": "Qatar", "value": "Qatar" },
  { "label": "Romania", "value": "Romania" },
  { "label": "Russia", "value": "Russia" },
  { "label": "Rwanda", "value": "Rwanda" },
  { "label": "Saint Kitts and Nevis", "value": "Saint Kitts and Nevis" },
  { "label": "Saint Lucia", "value": "Saint Lucia" },
  { "label": "Saint Vincent and the Grenadines", "value": "Saint Vincent and the Grenadines" },
  { "label": "Samoa", "value": "Samoa" },
  { "label": "San Marino", "value": "San Marino" },
  { "label": "Sao Tome and Principe", "value": "Sao Tome and Principe" },
  { "label": "Saudi Arabia", "value": "Saudi Arabia" },
  { "label": "Senegal", "value": "Senegal" },
  { "label": "Serbia", "value": "Serbia" },
  { "label": "Seychelles", "value": "Seychelles" },
  { "label": "Sierra Leone", "value": "Sierra Leone" },
  { "label": "Singapore", "value": "Singapore" },
  { "label": "Slovakia", "value": "Slovakia" },
  { "label": "Slovenia", "value": "Slovenia" },
  { "label": "Solomon Islands", "value": "Solomon Islands" },
  { "label": "Somalia", "value": "Somalia" },
  { "label": "South Africa", "value": "South Africa" },
  { "label": "South Korea", "value": "South Korea" },
  { "label": "South Sudan", "value": "South Sudan" },
  { "label": "Spain", "value": "Spain" },
  { "label": "Sri Lanka", "value": "Sri Lanka" },
  { "label": "Sudan", "value": "Sudan" },
  { "label": "Suriname", "value": "Suriname" },
  { "label": "Sweden", "value": "Sweden" },
  { "label": "Switzerland", "value": "Switzerland" },
  { "label": "Syria", "value": "Syria" },
  { "label": "Taiwan", "value": "Taiwan" },
  { "label": "Tajikistan", "value": "Tajikistan" },
  { "label": "Tanzania", "value": "Tanzania" },
  { "label": "Thailand", "value": "Thailand" },
  { "label": "Timor-Leste", "value": "Timor-Leste" },
  { "label": "Togo", "value": "Togo" },
  { "label": "Tonga", "value": "Tonga" },
  { "label": "Trinidad and Tobago", "value": "Trinidad and Tobago" },
  { "label": "Tunisia", "value": "Tunisia" },
  { "label": "Turkey", "value": "Turkey" },
  { "label": "Turkmenistan", "value": "Turkmenistan" },
  { "label": "Tuvalu", "value": "Tuvalu" },
  { "label": "Uganda", "value": "Uganda" },
  { "label": "Ukraine", "value": "Ukraine" },
  { "label": "United Arab Emirates", "value": "United Arab Emirates" },
  { "label": "United Kingdom", "value": "United Kingdom" },
  { "label": "United States of America", "value": "United States of America" },
  { "label": "Uruguay", "value": "Uruguay" },
  { "label": "Uzbekistan", "value": "Uzbekistan" },
  { "label": "Vanuatu", "value": "Vanuatu" },
  { "label": "Vatican City", "value": "Vatican City" },
  { "label": "Venezuela", "value": "Venezuela" },
  { "label": "Vietnam", "value": "Vietnam" },
  { "label": "Yemen", "value": "Yemen" },
  { "label": "Zambia", "value": "Zambia" },
  { "label": "Zimbabwe", "value": "Zimbabwe" }
]


export const appliances = [
  { value: "parking", label: "Parking" },
  { value: "flower", label: "Flower Garden" },
  { value: "swimming", label: "Swimming Pool" },
  { value: "internet", label: "Internet" },
  { value: "heating", label: "Heating" },
  { value: "dstv", label: "DSTV / Cables" },
  { value: "air", label: "Air Condition" },
  { value: "furnitures", label: "Furnitures" },
  { value: "pet", label: "Pet Friendly" },
  { value: "energy", label: "Energy Efficient" },
  { value: "gates", label: "Gated Residence" },
  { value: "servant", label: "Servant Quarters" },
  { value: "borehole", label: "Borehole" },
  { value: "waste", label: "Waste Management" },
];

export const commercialAppliances = [
  { value: "parking", label: "Visitor parkings" },
  { value: "heating", label: "Heating" },
  { value: "pet", label: "Pet Friendly" },
  { value: "borehole", label: "Borehole" },
  { value: "flower", label: "Flower Garden" },
  { value: "dstv", label: "DSTV / Cables" },
  { value: "energy", label: "Energy Efficient" },
  { value: "waste", label: "Waste Management" },
  { value: "swimming", label: "Swimming Pool" },
  { value: "air", label: "Air Condition" },
  { value: "internet", label: "Internet" },
  { value: "gym", label: "Gym" },
]

export const industrialAppliances = [
  { value: "parking", label: "Visitor parkings" },
  { value: "heating", label: "Heating" },
  { value: "pet", label: "Pet Friendly" },
  { value: "borehole", label: "Borehole" },
  { value: "green", label: "Green Spaces" },
  { value: "dstv", label: "DSTV / Cables" },
  { value: "energy", label: "Energy Efficient" },
  { value: "waste", label: "Waste Management" },
  { value: "swimming", label: "Swimming Pool" },
  { value: "air", label: "Air Condition" },
  { value: "internet", label: "Internet" },
  { value: "gym", label: "Gym" },
]

export const vacationalAppliances = [
  { value: "parking", label: "Visitor parkings" },
  { value: "heating", label: "Heating" },
  { value: "pet", label: "Pet Friendly" },
  { value: "borehole", label: "Borehole" },
  { value: "green", label: "Green Spaces" },
  { value: "dstv", label: "DSTV / Cables" },
  { value: "energy", label: "Energy Efficient" },
  { value: "waste", label: "Waste Management" },
  { value: "swimming", label: "Swimming Pool" },
  { value: "air", label: "Air Condition" },
  { value: "gates", label: "Gated Residence" },
  { value: "internet", label: "Internet" },
  { value: "gym", label: "Gym" },
]

export const landAppliances = [
  { value: "power", label: "Power Connected" },
  { value: "gates", label: "Gated Estate" },
  { value: "pet", label: "Pet Friendly" },
  { value: "borehole", label: "Borehole" },
  { value: "waste", label: "Waste Management" },
  { value: "internet", label: "Internet" },
  { value: "energy", label: "Energy Efficient" },
]
export const landUnits = [
  // { value: "Unit measurement", text: "Unit measurement" },
  { value: "Sqm", label: "Sqm" },
  { value: "Sqft", label: "Sqft" },
  { value: "ha", label: "ha" },
  { value: "Acres", label: "Acres" },
];

export const subscriptionPlans = [
  {
    name: "Standard",
    sell: "Everything to start",
    price: 0,
    PropertiesLimit: 3,
    imagesPropertiesLimit: 5,
    features: [
      "Free for lifetime",
      "Property Listing",
      "Property Details",
      "5 Images for Property",
      "3 Properties Limit",
      "Property Search",
    ],
  },
  {
    name: "Silver",
    sell: "Everything you need",
    price: 10,
    PropertiesLimit: 10,
    imagesPropertiesLimit: 10,
    features: [
      "Property Listing",
      "Property Details",
      "10 Images for Property",
      "10 Properties Limit",
      "Property Search",
      "24/7 Support",
    ],
  },
  {
    name: "Gold",
    sell: "Everything to sell all",
    price: 50,
    PropertiesLimit: 20,
    imagesPropertiesLimit: 25,
    features: [
      "Property Listing",
      "Property Details",
      "25 Images for Property",
      "20 Properties Limit",
      "Property Search",
      "24/7 Support",
      "Huge Discounts",
      "Personal Account Manager",
    ],
  },
];

const avatarColors = [
  "#ffdd00",
  "#fbb034",
  "#ff4c4c",
  "#c1d82f",
  "#f48924",
  "#7ac143",
  "#30c39e",
  "#06BCAE",
  "#0695BC",
  "#037ef3",
  "#146eb4",
  "#8e43e7",
  "#ea1d5d",
  "#fc636b",
  "#ff6319",
  "#e01f3d",
  "#a0ac48",
  "#00d1b2",
  "#472f92",
  "#388ed1",
  "#a6192e",
  "#4a8594",
  "#7B9FAB",
  "#1393BD",
  "#5E13BD",
  "#E208A7",
];

export { avatarColors };