import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import LayoutProvider from "@/providers/layout-provider";
import { ToastProvider } from "@/providers/toast-provider";
import Header from "@/components/landing/header";

const inter = Inter({ subsets: ["latin"] });

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunitosans",
});

const ibmPlex = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
  variable: "--font-ibmplex",
});

export const metadata: Metadata = {
  title: {
    default: "Home | African Real Estate",
    template: "%s | African Real Estate",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${nunitoSans.variable} antialiased`}>
          <ThemeProvider>
            <ToastProvider />
            <LayoutProvider>{children}</LayoutProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
